# Generated by Django 5.2 on 2025-04-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_contact_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=300)),
                ('M_name', models.CharField(max_length=300)),
                ('DOB', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=90)),
                ('category', models.CharField(max_length=30)),
                ('P_O_B', models.CharField(max_length=160)),
                ('M_no', models.BigIntegerField()),
                ('P_adhar', models.BigIntegerField()),
                ('C_adhar', models.BigIntegerField()),
                ('street', models.CharField(max_length=150)),
                ('landmark', models.CharField(max_length=140)),
                ('state', models.CharField(max_length=150)),
                ('pin_code', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
    ]
