# Generated by Django 5.2 on 2025-04-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='C_adhar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='registration',
            name='M_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='P_adhar',
            field=models.CharField(max_length=12),
        ),
    ]
