# Generated by Django 5.2 on 2025-04-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teach_sub', models.CharField(max_length=200)),
                ('expertise', models.CharField(max_length=200)),
                ('p_no', models.CharField(max_length=10)),
            ],
        ),
    ]
